### ISSUE TITLE
gitignore generated `craft-copy-transfer.sql`

### ISSUE THREAD

**Issue by tlimp** [fortrabbit/craft-copy#10]
This is only just a question:
Should the generated `storage/craft-copy-transfer.sql` be commited into source control or shoud it be `.gitignore`d?

**Comment by ostark** [comment]
It should be ignored 
```
*.sql
```
This is definitely missing here: 
https://github.com/fortrabbit/craft-copy/blob/master/src/.gitignore.example

Please keep the ticket open and add it manually for now.

**Comment by XhmikosR** [comment]
Personally I'm using this one in my root .gitignore

```
# CRAFT STORAGE
/storage/*
!/storage/.gitkeep
```
