### ISSUE TITLE
Environment check Warning for DB_TABLE_PREFIX is not useful

### ISSUE THREAD

**Issue by KarlBishop** [fortrabbit/craft-copy#101]
When I run the environment check `php craft copy` / `php craft copy/info` I get a warning for an unsynced local Environment Variable:

```
[WARNING] These local ENV vars are not in sync with the fortrabbit App:

           DB_TABLE_PREFIX=

           Copy the line above and paste it here:
           https://dashboard.fortrabbit.com/apps/myappname/vars
```

But if I try to copy and paste `DB_TABLE_PREFIX=` to the dashboard as instructed, it shows the error message:

`The value field is required.`

So this environment warning is not useful because it cannot be resolved without setting a value for DB_TABLE_PREFIX which I don't want or need. The environment check should ignore DB_TABLE_PREFIX when it is empty on local and unset on the remote.

**Comment by frank-laemmer** [comment]
I saw this today as well. I think it used to work at some point.

<img width="585" alt="Screenshot 2021-02-18 at 10 13 38" src="https://user-images.githubusercontent.com/962736/108341597-1a1f4c00-71da-11eb-8278-09d67ae1de1d.png">

**Comment by frank-laemmer** [comment]
The issue has been closed. The feature to check for the table prefix was removed. It was mostly required for pre Craft 3 Apps.
