### ISSUE TITLE
Issues with composer compatibility

### ISSUE THREAD

**Issue by fa6ian** [fortrabbit/craft-copy#104]
I tried running copy/code/up and hit this error

`Installing dependencies from lock file (including require-dev)
  Verifying lock file contents can be installed on current platform.
  Your lock file does not contain a compatible set of packages. Please run composer update.
  
    Problem 1
      - fortrabbit/craft-auto-migrate is locked to version 2.1.0 and an update of this package was not requested.
      - fortrabbit/craft-auto-migrate 2.1.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.    Problem 2
      - fortrabbit/craft-auto-migrate 2.1.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
      - fortrabbit/craft-copy 1.0.0-RC12 requires fortrabbit/craft-auto-migrate ^2.1 -> satisfiable by fortrabbit/craft-auto-migrate[2.1.0].
      - fortrabbit/craft-copy is locked to version 1.0.0-RC12 and an update of this package was not `requested.``

I've tried composer update, reinstalling 'Copy', and downgrading to composer 1. All to no avail.

**Comment by ostark** [comment]
Make sure to not define a fixed version in your composer.json. Use ^1.0.0 instead of 1.0.0-RC12, and run composer update -W
