### ISSUE TITLE
Craft Copy doesn't allow interaction with any branch besides `master`

### ISSUE THREAD

**Issue by raybrownco** [fortrabbit/craft-copy#105]
I just set up my first fortrabbit app and was really excited to try Craft Copy out. It looks like a really awesome plugin with a great developer experience! Unfortunately, I ran into a problem using it, and I've found that the issue stemmed from my git repo's default branch being named `main` instead of `master`. 

I've been using `main` instead of `master` for a while now, and there's a big push within the industry to stop using `master` as the default branch name [¹](https://www.bbc.com/news/technology-53050955) [²](https://www.theverge.com/2020/7/2/21311330/twitter-engineers-master-slave-github-programming-racism) [³](https://wptavern.com/proposal-to-rename-the-master-branch-from-wordpress-owned-git-repositories). However, this plugin currently seems to conflict with the `main` branch, and seems to only expect a `master` branch.

When I type `php craft copy/code/up` from the `main` branch, I see the following error: 

```
 [ERROR] Ooops.

error: src refspec master does not match any
error: failed to push some refs to 'deploy.us1.frbit.com:[APP_NAME].git'
```

Upon inspection of the plugin code, I see that it's trying to run `git push -u [APP_NAME] master`. When I try to run the same command from the terminal, I see the same error (minus the plugin's "Ooops" line). The error is pretty clear: `src refspec master does not match any`. It's looking for the `master` branch, which doesn't exist.

Next, I created a new branch called `master` from `main`, and i re-ran the `php craft copy/code/up` command. It worked like a charm:

```
–––––––––––––––––––––––  ∙ƒ  –––––––––––––––––––––––

To deploy.us1.frbit.com:[APP_NAME].git
   d07eea7..be12d1e  master -> master

 [OK] Code deployed successfully.
 ```
 
 I'm glad to have figured the issue out, but I suspect that a lot of other people may be running into the same issue. It seems that you could pretty easily prompt the user for the name of the branch that they wish to use for deployments (or at least determine if the `master` branch exists before trying to push from it). I'd love to hear how likely this is to happen. 
 
 Also, please let me know if you'd like any other info about my local setup. 
 
 Finally, keep up the great work! This tool is awesome and I hope to settle into fortrabbit for all of my Craft CMS needs. ✌️

**Comment by frank-laemmer** [comment]
Thanks for the nice write-up. 

We are aware of the change going forward from `master` to `main` in Git repos. But currently this is not supported at fortrabbit at all. With fortrabbit you can have any branches, but only the `master` branch will deploy code to the App. There is an internal IDEA ticket to also deploy from the `main` branch at fortrabbit, but currently there is no ETA for that. So, as long as that is the case, Craft Copy can safely assume `master`.

https://help.fortrabbit.com/git-deployment#toc-the-branch-name-counts

There is one exception though, listed with the linked headline above. It should actually also respect the exact App name as a branch to deploy from. That is expected to work (I think).

I leave this open for review by @ostark. The issue might get closed for now.

**Comment by frank-laemmer** [comment]
FYI: The main branch is now also support by fortrabbit.

**Comment by raybrownco** [comment]
Thanks for following up on this, @frank-laemmer!
