### ISSUE TITLE
Script copy/all/up always fails

### ISSUE THREAD

**Issue by TheFunkyMonk** [fortrabbit/craft-copy#111]
## Issue

I've set up a handful of Craft sites on Fortrabbit, and it seems like the `copy/all/up` script in this plugin always fails when initially deploying the site after using `php craft copy/setup`. This time, I'm not actually sure how to proceed.

## Steps to reproduce

1. Run setup steps from `php craft copy/setup` and select yes to push everything up with `copy/all/up`.
2. The code deploys and I get an error on Craft auto migrate that it can't connect to the database, which makes sense at this point given the database hasn't been pushed up. 
2. After the error stack trace, I still see `[OK] Code deployed successfully`, and setup moves to the next step of exporting the local database and pushing it up to fortrabbit.
3. On attempting to push up the database, I receive: `[ERROR] Unable to import database. Deploy code first using this command: php craft copy/code/up`

I understand there's a bit of a chicken and egg problem referenced in [this issue](https://github.com/fortrabbit/craft-copy/issues/85), but even running `php craft copy/db/up --force` at this point results in the same error message from step 4.

If I SSH into the app, I see my code and it looks like the files in `vendor` have been installed. What is the recommended way to proceed from here?

**Comment by ostark** [comment]
Sorry, this issue was related to the delayed database provisioning.
I answered in support.

**Comment by Maybach91** [comment]
I have the same issue, what can i do to solve this? @ostark

**Comment by ostark** [comment]
@Maybach91 
any luck with?:

```
 php craft copy/db/up --force
```

**Comment by Maybach91** [comment]
> @Maybach91 
> 
> any luck with?:
> 
> 
> 
> ```
> 
>  php craft copy/db/up --force
> 
> ```

Thanks for the help, but no, i get the same error. :/
