### ISSUE TITLE
Question: does it matter if yaml changes are updated before or after database import?

### ISSUE THREAD

**Issue by andreimoment** [fortrabbit/craft-copy#113]
In a scenario where I made some structural changes on dev, and then some content changes on dev, I am wondering if these two workflows would produce the same result or not:

A. Deploy code, apply yaml, import database

B. Deploy code,  import database, apply yaml

Any advice on using one or the other?

**Comment by ostark** [comment]
I think it does not matter. In theory, the final state is the same.
