### ISSUE TITLE
Exclude a table with db/all up?

### ISSUE THREAD

**Issue by DigitalRebelMarketing** [fortrabbit/craft-copy#115]
Is there a way to exclude certain tables when using the copy/all/up or the copy/db/up?

**Comment by frank-laemmer** [comment]
Currently there is no way to exclude certain tables for `copy/db/up` or `copy/db/down` (included in all). Maybe provide more details about your use case. What do you want to exclude and why?

**Comment by DigitalRebelMarketing** [comment]
One case I'm looking at is storing form submissions (or other data) in a DB Table.  Currently, I would have to pull down that table manually to dev before pushing it out again where it will override the prod table.

**Comment by tomdavies** [comment]
Using `copy/all/up` or `copy/db/up` is always going to be inherently risky for a site that is live (and thus receiving content edits from someone other than the developers.

The expected workflow for `copy/db/up` is for development prior to site launch, or for moving the database between stages / environments. It is not intended as the primary way to deploy changes to the db in live.

For that you should be using [Craft's project config](https://craftcms.com/docs/3.x/project-config.html) and then running migrations in production to apply those changes. 

 As such the requested feature not something we are likely to implement, sorry!
