### ISSUE TITLE
Migrate to symplify/git-wrapper

### ISSUE THREAD

**Issue by tomdavies** [fortrabbit/craft-copy#117]
[cpliakas/git-wrapper](https://packagist.org/packages/cpliakas/git-wrapper) is marked as abandoned on Packagist

[symplify/git-wrapper](https://packagist.org/packages/symplify/git-wrapper) is front the same author and recommended as migration path

TODO: confirm API changes, if any

**Comment by ostark** [comment]
This will happen with the next major release https://github.com/fortrabbit/craft-copy/pull/135
