### ISSUE TITLE
Composer versioning conflict with `vlucas/phpdotenv`

### ISSUE THREAD

**Issue by chagers** [fortrabbit/craft-copy#127]
## Issue
Attempting to install craft-copy on my project, and unable to resolve a version conflict.
I've followed suggestions in the README, and in an old issue (#67), without luck.

Using the following craftCMS and PHP versions:
- `Craft CMS 3.7.26`
- `PHP 7.4.21`

## Error
```
$ composer require fortrabbit/craft-copy -W
Using version ^1.0 for fortrabbit/craft-copy
./composer.json has been updated
Running composer update fortrabbit/craft-copy --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fortrabbit/craft-copy[1.0.0, ..., 1.0.7] require vlucas/phpdotenv ^2.5.1 | ^3.4.0 -> found vlucas/phpdotenv[v2.5.1, ..., v2.6.9, v3.4.0, ..., v3.6.10] but it conflicts with your root composer.json require (^5.0).
    - Root composer.json requires fortrabbit/craft-copy ^1.0 -> satisfiable by fortrabbit/craft-copy[1.0.0, ..., 1.0.7].```

**Comment by frank-laemmer** [comment]
How old is the version of Craft CMS you are having there? I see you are on a recent version now, but is that a new installation or have you been updating it?

**Comment by frank-laemmer** [comment]
This might or might not help, but maybe worth a try. 

In the files `web/index.php` and in `craft`. Find the configuration for `vlucas/phpdotenv`. See if the "Old syntax" exists and replace it with new suggested syntax.


## Old (remove)

```php
// Load dotenv?
if (file_exists(CRAFT_BASE_PATH.'/.env')) {
    (new Dotenv\Dotenv(CRAFT_BASE_PATH))->load();
}
```

## New (insert)

```php
// Load dotenv?
if (class_exists('Dotenv\Dotenv') && file_exists(CRAFT_BASE_PATH.'/.env')) {
  DotEnv\DotEnv::create(CRAFT_BASE_PATH)->load();
}
```

**Comment by chagers** [comment]
Thanks for your help, I've actually been using `Craft 3.7.26` from the start of my project, and don't have either the 'old' or 'new' syntax in my `web/index.php` / `craft` files. It seems Craft may have changed this in a recent update?

I checked with a teammate, and they have the code you mentioned (new version) in their install from a little while back, but in my new project (and if I do a fresh test install from Composer) the entire contents of my `web/index.php` file are:

```
<?php
/**
 * Craft web bootstrap file
 */

// Load shared bootstrap
require dirname(__DIR__) . '/bootstrap.php';

// Load and run Craft
/** @var craft\web\Application $app */
$app = require CRAFT_VENDOR_PATH . '/craftcms/cms/bootstrap/web.php';
$app->run();
```

The only place I can find mention of `Dotenv` is in the `bootstrap.php` file:
```
<?php
/**
 * Shared bootstrap file
 */

// Define path constants
define('CRAFT_BASE_PATH', __DIR__);
define('CRAFT_VENDOR_PATH', CRAFT_BASE_PATH . '/vendor');

// Load Composer's autoloader
require_once CRAFT_VENDOR_PATH . '/autoload.php';

// Load dotenv?
if (class_exists('Dotenv\Dotenv')) {
    Dotenv\Dotenv::createUnsafeImmutable(CRAFT_BASE_PATH)->safeLoad();
}

// Define additional PHP constants
// (see https://craftcms.com/docs/3.x/config/#php-constants)
define('CRAFT_ENVIRONMENT', getenv('ENVIRONMENT') ?: 'production');
```

**Comment by ostark** [comment]
Hi @chagers 

Can you please show the section that defines the "vlucas/phpdotenv" dependency in your composer.json?

**Comment by ostark** [comment]
> This might or might not help, but maybe worth a try.
> 
> In the files `web/index.php` and in `craft`. Find the configuration for `vlucas/phpdotenv`. See if the "Old syntax" exists (this might be the case when your Craft installation is older) and replace it with new suggested syntax.

@frank-laemmer 
FYI; Most recently, Craft's dotenv loader moved to a shared boostrap.php file
https://github.com/craftcms/craft/blob/main/bootstrap.php

**Comment by chagers** [comment]
That worked! Thanks so much 🚀
