### ISSUE TITLE
./nitro-craft copy/db/down asks for deploy.eu2.frbit.com's password

### ISSUE THREAD

**Issue by howells** [fortrabbit/craft-copy#129]
Having installed the Nitro wrapper and running a copy command, I'm asked for my app's password (****@deploy.eu2.frbit.com), which I obviously don't have. I thought it might be my key's password, but that doesn't work.

Have I missed something here?

**Comment by howells** [comment]
I assume this means my keys haven't been transferred? How would I do that?

**Comment by ostark** [comment]
Sorry, I missed your issue.
Does the problem remain?

**Comment by howells** [comment]
@ostark I gave up on Nitro and ended up using ddev instead.
