### ISSUE TITLE
Running the `./nitro-craft copy` results in a new docker image being built.

### ISSUE THREAD

**Issue by andreimoment** [fortrabbit/craft-copy#143]
MacOS 12.4 on M1 Max.

Running the `./nitro-craft copy` results in a new docker image being built.

```
➜  myproject git:(master) ./nitro-craft copy
Checking host ssh-agent, you may be prompted for your SSH key password...
4096 SHA256...(RSA)
Building docker container image, please be patient...
```
and, when I look at the docker images, I see a few which may be the result of this command. 

Any ideas about why this is happening, guidance to prevent the creation of new images?

Or, are there images that can be safely deleted?

![image](https://user-images.githubusercontent.com/6190/177633528-4a970176-80a8-4fd5-a656-2129a83bb3d3.png)

**Comment by esbiorn** [comment]
This is expected. We build an image specifically for your project, with your PHP version and the correct version of craft copy to match the version you have included in your composer.json. As with other docker builds, the image will only be built the first time, and later runs will reuse the same image. When you change the PHP version or craft copy version, a new slightly different image will be built.

Our image is very small and only contains a few packages and scripts on top of the default `craftcms/cli` image. So the actual added size from our image is only a few megabytes. Our images are always named as `ghcr.io/fortrabbit/craft-copy`. The size you see in that list is the total size from all layers, so most of that is actually shared between images.

If you still need to clean up space, you can usually delete all images from your docker and they will automatically be rebuilt as needed. That is at least the case for our images, they are rebuilt on demand.

**Comment by frank-laemmer** [comment]
We are closing this, since Nitro is supported/maintained any more.
