### ISSUE TITLE
Question: Is craft-copy compatible with DDEV?

### ISSUE THREAD

**Issue by andreimoment** [fortrabbit/craft-copy#145]
Seems like nitro is being retired and DDEV is the recommended replacement. 

Is craft-copy compatible with DDEV?

There are instructions in the Readme for installing on nitro. I don't see anything about DDEV and so I am not sure if it's safe to move forward.

Thank you.

**Comment by ostark** [comment]
There is an older article about DDEV 
https://blog.fortrabbit.com/local-craft-dev-site-ddev-development-tool

So far it requires to ssh into the container. We are about to review the article (not sure if everything is still correct). If you have ideas to make the setup easier, please let us know.
