### ISSUE TITLE
craft-copy using a different server root than app itself

### ISSUE THREAD

**Issue by Maybach91** [fortrabbit/craft-copy#150]
I have set the document root of the App to `htdocs/web`. To access craft and its assets the server has to point to the `web` folder, according to the [craft documentation](https://craftcms.com/docs/4.x/installation.html#step-5-set-up-the-web-server).
So the setting `WEB_ROOT_PATH=.` works fine to access the app as well in my local environment. 

But when i want to get the assets from the server to local via `php craft copy/volumes/down production` it tries to access the path `htdocs/assets/...` instead of `htdocs/web/assets/...`. Which leads to no pulling/rsync.

When craft-copy shows the following directory in the cli, **its working ↓**. (local env `WEB_ROOT_PATH=web`)
```
+------------+---------------------------+
| Volume     | blog                      |
+------------+---------------------------+
| Directory  | ./web/assets/blog/        |
```

If using the setting `WEB_ROOT_PATH=.` its **not working ↓**. But accessing the website and its assets is working.
```
+------------+---------------------------+
| Volume     | blog                      |
+------------+---------------------------+
| Directory  | ./assets/blog/            |
```

It feels wrong to change the env explicit for the craft-copy cli. And i was wondering if i’m doing something wrong.  My fortrabbit config only contains the `app`, `ssh_url`, `git_remote` and `before` `after` commands.

**Comment by ostark** [comment]
Hi @Maybach91 - it's not forgotten, we are trying to reproduce it.

**Comment by ostark** [comment]
Hi @Maybach91,

IMO there is no need to set the WEB_ROOT_PATH at all. 
You may define the `@webroot` alias 
https://help.fortrabbit.com/craft-tune#toc-domain-setup

**Comment by Maybach91** [comment]
> Hi @Maybach91,
> 
> IMO there is no need to set the WEB_ROOT_PATH at all. You may define the `@webroot` alias [help.fortrabbit.com/craft-tune#toc-domain-setup](https://help.fortrabbit.com/craft-tune#toc-domain-setup)

Thanks for the hint @ostark . I’m already using this. I’m using [this](https://github.com/nystudio107/craft/blob/craft-vite/cms/config/general.php) config. Or is this something different from that, what you are suggesting? 🤔

**Comment by frank-laemmer** [comment]
We don't understand your problem still. Can you elaborate?

**Comment by frank-laemmer** [comment]
Closing after no reply. Sorry not actionable.
