### ISSUE TITLE
Document feature removing old project.yml files (auto-migrate) 

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#152]
As far as I understand, with [this change](https://github.com/fortrabbit/craft-copy/pull/149), all old `project.yml` are going to get wiped and replaced with new ones to avoid conflicts (due to overwrite but not delete feature on fortrabbit).

This is a request to document the behaviour with the README file. I understand that it is a feature with auto migrate. Might be added to both READMEs.

**Comment by ostark** [comment]
I did the change here: https://github.com/fortrabbit/craft-copy/commit/39662221ccc107b7097ecb8ea3bc97a8a644389b
