### ISSUE TITLE
Add branch option for copy/code/up

### ISSUE THREAD

**Issue by joshuabaker** [fortrabbit/craft-copy#16]
Allow adding branches to `php craft copy/code/up {localBranch} {remoteBranch}` to avoid question interface, which currently throws an exception when used in a Composer script.

**Comment by ostark** [comment]
My idea is to introduce "environment configs", like this one:
https://github.com/fortrabbit/craft-copy/blob/multienv/src/example-env.copy.yaml

**Comment by ostark** [comment]
@joshuabaker  Can you explain your workfow?

**Comment by joshuabaker** [comment]
@ostark In summary `composer deploy`, which means that input has to be via arguments.

**Comment by ostark** [comment]
@joshuabaker 
```
php craft copy/code/up --interactive=0
```
this should pick your current head + remote tracking

**Comment by ostark** [comment]
or use

**Comment by joshuabaker** [comment]
I found that somewhere, however, that requires your current head to be on `master` like you mention.

This is what I’m using right now, which side steps the plugin entirely.

```json
"deploy-to-production": [
  "git push production master:master",
  "rsync -av ./web/dist/ app@deploy.eu2.frbit.com:~/web/dist/ --exclude=.DS_Store"
]
```
