### ISSUE TITLE
Print a warning when no SSH key is used

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#164]
To avoid customer support cases, Craft Copy could be forthcoming and print a warning, if a user is attempting to use Craft Copy with username/password (not support).

I don't if that is possible and how it would be done, but currently it fails not so nice. It seems to ask for a password, while no password will work at all.

**Comment by frank-laemmer** [comment]
I see this has been requested by me before: https://github.com/fortrabbit/craft-copy/issues/91

**Comment by frank-laemmer** [comment]
Discussed today: Should be easy to test one more time.

**Comment by ostark** [comment]
https://github.com/fortrabbit/craft-copy/pull/174
