### ISSUE TITLE
Non-Interactive for rSync?

### ISSUE THREAD

**Issue by MacroFabMktg** [fortrabbit/craft-copy#169]
When using copy/all/up or copy/all/down is there a way to automatically accept all volumes without interactivity to sync volumes?

**Comment by pheeque1** [comment]
You should be able to do that by disabling interactivity with `i=0`.

More information [here](https://github.com/fortrabbit/craft-copy#options-and-arguments-1).

**Comment by ostark** [comment]
Hi @MacroFabMktg 

at the moment we don't pass the i=0 flag to the sub-commands.
we are looking forward to providing this (if it does not break any existing workflows)


Oli

**Comment by ostark** [comment]
Please let us know if it works as expected using the latest release 
https://github.com/fortrabbit/craft-copy/pull/173
