### ISSUE TITLE
Feature request: multi-environment sync

### ISSUE THREAD

**Issue by kot-behemoth** [fortrabbit/craft-copy#17]
Hi, and firstly — thanks for such a great tool as craft/copy. It really made developing with Craft a pleasure!

I have what I feel is a feature request. I hope it makes sense, I as this is a bit of a compilation of several thought. I'm happy to clarify if needed.

- I use your craft-copy tool extensively to sync DBs between two environments: staging and production. Currently, via local machine. I.e. I do sync/down from staging to local, then sync/up from local to production.
- My aim is to allow the client seamlessly write content/do changes on staging environment. After finishing, they would press a button either in the Control Panel, or the app console to push the changes from staging to production.
- Since the project will be handed over to the client, and mostly used by non-technical people, I'm looking for a simple deploy workflow. And by deploy I mean syncing the DB from staging to production - as it'll be only entries and settings changes. The important point here, is that sync should be ran on the production box, pulling DB changes from staging. To clarify: this should not be a sync/down from staging to local machine, then sync/up from local to production.

The goal is to have CLI-free DB migration from staging to production. I’m essentially looking for creating that workflow available from Craft’s control panel. 

To give a more concrete example, I’m looking to build a button for a non-technical editor. When they finish writing an article on Staging, they can test it all looks great and works. I want them to then have a button somewhere in CP that, when pressed, simply copies staging DB over to production. It feels like craft/copy tool could provide the functionality for that. Obviously, the button could be implemented as a plugin separately.

Does that use-case make sense, or am I overcomplicating it? Craft development is not my specialty, so I apologise in advance.

**Comment by ostark** [comment]
Hi Greg,

That kind workflow (write content on staging and sync it with prod to publish) is not really the scope of that plugin. IMO, the editors should produce content on the production site. With the live preview you can see how (unpublished) content looks like, and then you can publish it by changing the state/visibility.

I think that's the most common way to do that.
Just let me know why this will not work for you.

Oli

**Comment by kot-behemoth** [comment]
Apologies for taking so long to get back to you! 

Thanks for your response. It makes sense, and made me rethink how I will define publishing workflow for the editors following your suggestions. 

The only time there's a real need of pushing staging to production is when there are some actual dev changes. And then the devs will use this tool as it already functions. So, no problem there. 

Thanks, and feel free to close the ticket!

Greg
