### ISSUE TITLE
Copy v2.4.1 no longer providing deploy feedback in terminal

### ISSUE THREAD

**Issue by turnstylerj** [fortrabbit/craft-copy#171]
After updating from Copy 2.3.2 => 2.4.1, I'm no longer getting feedback in my terminal on `php craft copy/code/up` including the build/composer/Craft scripts running. I see:
```
git push (empty commit)
-----------------------
```
Then it just hangs for a while until the process completes and I get:
```
[OK] Code deployed successfully.
```

**Comment by dgaidula** [comment]
just installed v2.4.2 and it is exhibiting the same behavior. Hangs then [OK] Code deployed successfully.
