### ISSUE TITLE
DDEV unable to setup craft-copy:  [ERROR] ⚠  App not found

### ISSUE THREAD

**Issue by Wttewaall** [fortrabbit/craft-copy#172]
I'm using DDEV as my local setup and the project is on Craft CMS.
I have a local ssh key and added it to my account on Fortrabbit.
I've read and tried everything on https://blog.fortrabbit.com/local-craft-dev-site-ddev-development-tool

Frank helped me by pointing out that I needed to run `ddev auth ssh` and enter the local container by running `ddev ssh`.
From within the container I was able to ssh into the Fortrabbit web server, which means ddev has ssh key access.

On my local container (ddev ssh) I then ran `php craft copy/setup`.
The script asks for the App name, but fails to find it, returning `[ERROR] ⚠  App not found`.

As a side note, at first I tried executing copy via DDEV's craft command: `ddev craft copy/setup`, but that resulted in the same issue.

**Comment by ostark** [comment]
We believe this issue is related to your DNS setup and is not a common problem. We replied to your support request.
