### ISSUE TITLE
copy v2.4.2 no longer providing feedback in terminal for copy/code/up

### ISSUE THREAD

**Issue by dgaidula** [fortrabbit/craft-copy#175]
Exact same issue as described here.

https://github.com/fortrabbit/craft-copy/issues/171

**Comment by turnstylerj** [comment]
![2023-08-07 at 10 32 01@2x](https://github.com/fortrabbit/craft-copy/assets/42223501/2a092651-f518-4136-b8ce-0b426c0dbf82)

Yeah, not really sure why the original issue was closed. But I'm experiencing this on another project as well.

**Comment by ostark** [comment]
Thanks, @dgaidula & @turnstylerj for highlighting the behavior.

I'll try to reproduce it this week - sorry for the delay.

**Comment by ostark** [comment]
We are working on it to bring back the composer output.
This was an unintended regression.
