### ISSUE TITLE
Failed to Copy DB When Deploying to Production

### ISSUE THREAD

**Issue by MacroFabMktg** [fortrabbit/craft-copy#176]
I'm getting the following error when I try to deploy to production.  Staging works just fine.  This happens on copy/all, copy/db and using --force command.  Any ideas why this would be happening on one instance, but not the other?
Using:
"craftcms/cms": "4.5.3",
"fortrabbit/craft-copy": "2.4.2"

I also checked to insure that the craft-copy-import-db.php exists in both the vendor/bin and vendor/fortrabbit/craft-copy/bin directory and code exists.

![image](https://github.com/fortrabbit/craft-copy/assets/118196177/bc4cd5c6-f5e0-4efc-b950-834c41e2bd82)

**Comment by MacroFabMktg** [comment]
Using:
"craftcms/cms": "4.5.3",
"fortrabbit/craft-copy": "2.4.2"

**Comment by MacroFabMktg** [comment]
After a day and a half, I was able to push without issue.  Not sure what happened. Self-Closing this issue.

**Comment by frank-laemmer** [comment]
Thanks!
