### ISSUE TITLE
Not deploying correct branch

### ISSUE THREAD

**Issue by agrigg** [fortrabbit/craft-copy#181]
I'm using craft-copy 1.2.4 (since my project is using Craft 3). I've run copy/setup to setup my staging environment. 

When I run `php craft copy/code/up staging` it asks me which branch I want to deploy and I choose the current feature branch I'm working on called "campuses". It says it deploys the code successfully, but when I check on the FTP it doesn't look like it has deployed my changes from the "campuses" branch, but it looks like what is on master.

Do I have to merge my changes into my local master branch before using craft-copy or can I deploy from my feature branch?

**Comment by dgaidula** [comment]
yes, prior to v2 craft-copy will only push/pull master branch.
see my backport of the v2 features, I'm waiting for them to pull this.
https://github.com/fortrabbit/craft-copy/pull/180

**Comment by agrigg** [comment]
Nice thanks for confirming @dgaidula! Hopefully those changes will get merged in soon as that would be a big help.

**Comment by ostark** [comment]
Merged and released as `1.2.5` - thanks @dgaidula for this contribution!
