### ISSUE TITLE
Volumes File Permissions

### ISSUE THREAD

**Issue by cgdurha2** [fortrabbit/craft-copy#183]
Since upgrading to v2.4.3, anytime I use `copy/all/up` or `copy/volumes/up`, it works correctly, but all of my assets are uploaded with the wrong permissions, and I have to then ssh into the production and reset the file permissions of all of my volumes.

I'm doing that by executing these two lines of code `find . -type d -exec chmod 0755 {} \;` `find . -type f -exec chmod 0644 {} \;`, but this wasn't an issue before the upgrade, and I have correctly set the permissions on my local dev instance before pushing them to production, so I'm wondering if this is a bug or is intentional. Anyone else having an issue with this? It's happening with all my fortrabbit apps.

**Comment by ostark** [comment]
In 2.4.3 we did not touch the `copy/volumes/up` command.
Since you are the only one with this issue, I assume it's related to your local machine somehow.

**Comment by frank-laemmer** [comment]
I am re-opening the issue, since I believe it's not fixed yet. Multiple clients reported the issue in our support. We tried to replicate it, yet we haven't been able to.

The important part to note is that the issue appears in combination with DDEV.

**Comment by brycekirk** [comment]
Is there still no fix for this?
