### ISSUE TITLE
Default answer to "Are you sure?" should not be "yes"

### ISSUE THREAD

**Issue by sonniesedge** [fortrabbit/craft-copy#22]
Lovely tool - I use it a lot and it's very reliable.

However the default answer to "Are you sure?" after being asked if a user wishes to import is dangerous.

It should be "no".

I almost lost my Craft DB on Fortrabbit after installing craft-copy on a local machine. It ran through the install script and at the end asked:

```
$ php craft copy/db/up

Export local DB - import on remote: sonniesedge
-----------------------------------------------

 Are you sure? (yes/no) [yes]:

```

If I had accidentally hit return here I would have lost my live site, having it replaced by an empty DB that was sitting on my machine.

## Summary

Can we please make the default response to be "no" to avoid situations like this? Explicit confirmation should always be required for a data-destroying operation.

**Comment by ostark** [comment]
👍Thanks for sharing your experience. This should be easy to fix.

**Comment by ostark** [comment]
Changed to "no" in RC1, except when the --force option is used.
