### ISSUE TITLE
Before/after scripts fail, when there's a question in the process

### ISSUE THREAD

**Issue by JuhG** [fortrabbit/craft-copy#28]
I've tried to use before/after scripts similar to your [example config](https://github.com/fortrabbit/craft-copy/blob/master/src/fortrabbit.example-config.yaml) but assets/up failed with a simple 'ERROR'.

I went after the issue and it looks like the question 'Are you sure?' causes the problem. Automatically answering it or giving an option to the user to predefine it in the config file might be a solution. The process class already has the [option to do that](https://symfony.com/doc/current/components/process.html#streaming-to-the-standard-input-of-a-process). (That would require to change the yaml file structure slightly.)

Can you confirm that this is the problem?

(Awesome plugin btw!)

**Comment by ostark** [comment]
Thanks for your input. Can you elaborate the change of the structure?

**Comment by JuhG** [comment]
I was thinking of something like this: 

```yaml
# Scripts
before:
  code/up:
    - "npm run prod"
    - script: "php craft copy/assets/up production web/build/prod"
      input: "yes"
```

But then I found the interactive flag, which solves this particular issue.
```yaml
    - "php craft copy/assets/up production web/build/prod --interactive=0"
```
Maybe in another case - where you don't want to select the default option - this could be helpful.

But the example config should definitely be updated, since it doesn't work in the current form.

**Comment by JuhG** [comment]
Alright. If you think my suggestion makes sense it should be backwards compatible with the current form with a simple is_array check. If you're open to it, I can send a change request to solve it.
