### ISSUE TITLE
"failed to install copy" error

### ISSUE THREAD

**Issue by frankharrison** [fortrabbit/craft-copy#33]
Hi

I'm trying to install this for the first time. I've got as far as `php craft install/plugin copy` but I then get the output you mention in the Troubleshooting section:
```
*** installing copy
*** failed to install copy: Craft CMS can’t connect to the database with the credentials in config/db.php.
```
So I did the suggested fix of `Ensure "Allow network access to MySQL" is ticked in MAMP`... but I'm still getting the same error. I've tried restarting the server but that doesn't seem to help.

Any ideas what I should try next?

Thanks, and looking forward to using this – looks super helpful!

**Comment by ostark** [comment]
Nothing I can think of so far.
Does this command work or do you get the same error?

```
php craft update
```

**Comment by frankharrison** [comment]
Aha – `php craft update` said Craft wasn't installed (even though Craft is running fine). I ran `craft setup` and that seems to have done the trick – `php craft update` and `php craft install/plugin copy` both work now. Very strange as it didn't change anything in my .env file. But all seems good now – thank you!

**Comment by frankharrison** [comment]
Actually spoke too soon! When I go through the `php craft copy/setup` process I get
```
Testing DNS - US (AWS US-EAST-1 / Virginia) OK
Testing rsync OK
Testing mysqldump OK
Testing SSH access OK
[ERROR]
         fortrabbit\Copy\exceptions\DeployConfigNotFoundException
         in
         /path_to_local_craft_install/vendor/fort
         rabbit/craft-copy/src/services/DeployConfig.php: 128
```
I don't know if this is relevant but Craft isn't in the top-level folder of my repo – it's in a `dist` folder. Any idea what the problem might be?

**Comment by ostark** [comment]
Hi Frank,

I hope RC5 solves it for you (please update)
https://github.com/fortrabbit/craft-copy/releases/tag/1.0.0-RC5

Oli

**Comment by ostark** [comment]
Duplicate https://github.com/fortrabbit/craft-copy/issues/34
