### ISSUE TITLE
Install errors ("The plugin is not installed with your App!", "Uncommitted changes") 

### ISSUE THREAD

**Issue by frankharrison** [fortrabbit/craft-copy#37]
Hi

I'm getting a couple of issues when trying to install.

After running `php craft copy/setup` I get:
```
Testing DNS - US (AWS US-EAST-1 / Virginia) OK
Testing rsync OK
Testing mysqldump OK
Testing SSH access OK
 The plugin is not installed with your App! Do you want to deploy now? (yes/no)
```
... which is odd as the Copy plugin shows as installed both locally and on the staging server. If I choose "yes" I get the following:
```
 ░ [NOTE] Uncommitted changes:
 ░        ?? .env.example
 ░        ?? .gitignore
 ░        ?? composer.json
 ░        ?? composer.lock
 ░        ?? config/
 ░        ?? craft
 ░        ?? craft.bat
 ░        ?? modules/
 ░        ?? storage/
 ░        ?? templates/
 ░        ?? web/
```
... which is also odd as all of those files are committed in my repo and exist locally and on the staging site. I'm wary of entering a commit message at this point in case it does something bad to the files on the staging server.

Is something wrong in my config/setup? I don't know if it's relevant but Craft is installed in a `dist` subdirectory. So GIT is tracking a directory containing:
```
fortrabbit.yml
dist
  composer.json
  composer.lock
  config
  craft
  craft.bat
  modules
  storage
  templates
  vendor
  web
gulpfile.js
node_modules
package-lock.json
package.json
README.md
src
```
Do I need to do something special since Craft isn't in the root?

I'm on Craft CMS 3.1.28, Copy 1.0.0-RC5. Thanks loads for any help.

**Comment by ostark** [comment]
We expect `composer.lock` and `composer.json` at the root level of your project to run `composer install` to install Composer packages (Craft + Plugins + Dependencies).

**Comment by frankharrison** [comment]
@ostark thanks. In that case I'm not quite sure what to do. I really like Craft being in its own `dist` directory – I've got a bunch of Gulp tasks that process files from `src` and put them in there. With previous hosts I've just rsynced the `dist` directory so it's been nice and clean. And my GIT repo has always been the entire root directory, including src files.

I like the idea of using GIT to deploy to Fortrabbit, and would love to use this plugin also, but is that just not possible with this kind of setup?

**Comment by frankharrison** [comment]
@ostark sorry to bump, but hoping to get this site live soon so would be great to figure out the best approach here. Do you have any thoughts on getting it working with Craft installed in a subdirectory of the repo's directory?

**Comment by ostark** [comment]
Well, adding a variable subdirectory would add a lot of overhead.
Instead you could
```
cd dist
git init
git remote add fr app@host
```

**Comment by frankharrison** [comment]
In the end I decided to restructure so Craft is in the root. All working great now – thanks!
