### ISSUE TITLE
"Changes to project.yaml must be applied to the loaded project config"

### ISSUE THREAD

**Issue by frankharrison** [fortrabbit/craft-copy#38]
Whenever I push new code, my site goes offline until I go to the CP, where I get:
```
Changes to project.yaml must be applied to the loaded project config
[Sync changes]
```
... followed by
```
The loaded project config has more recent changes than project.yaml.
[Use the loaded project config] [Use project.yaml]
```
I don't know if this is an issue with Craft or Craft Copy but have you encountered this before? And idea for a fix?

Thanks for this plugin – apart from this little glitch it's improved my deployment process massively!

**Comment by ostark** [comment]
@frankharrison
I was able to reproduce the issue, eventually. The latest release (full rewrite of `fortrabbit/craft-auto-migrate`) should fix it.

**Comment by frank-laemmer** [comment]
As noted in related cases: Fix seems to work for me.
