### ISSUE TITLE
Better error when no SSH key is installed

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#49]
When a user does not have an SSH key installed, this error is shown:

![Screenshot 2019-09-30 at 13 22 15](https://user-images.githubusercontent.com/962736/65874184-7c797180-e385-11e9-96cc-a51f224fe971.png)

The error message "SSH is required" is not super helpful here. Could be "SSH key authentication is required here, username/password authentication is not working. Please add your SSH key to your fortrabbit Account first."

**Comment by ostark** [comment]
This error is not directly related to the (missing) ssh key, but it's very likely this is the issue.

**Comment by frank-laemmer** [comment]
Current status: Waiting for PR review.
