### ISSUE TITLE
Conflict with Blitz plugin

### ISSUE THREAD

**Issue by joshuabaker** [fortrabbit/craft-copy#60]
The shared dependency `cpliakas/git-wrapper` causes a conflict when requiring Copy after installing the Blitz plugin.

```
Problem 1
  - Installation request for fortrabbit/craft-copy ^1.0.0-RC10 -> satisfiable by fortrabbit/craft-copy[1.0.0-RC10].
  - Conclusion: remove cpliakas/git-wrapper v3.0.2
  - Conclusion: don't install cpliakas/git-wrapper v3.0.2
  - fortrabbit/craft-copy 1.0.0-RC10 requires cpliakas/git-wrapper ^2.0 -> satisfiable by cpliakas/git-wrapper[v2.0.0, v2.0.1, v2.1.0, v2.2.0].
  - Can only install one of: cpliakas/git-wrapper[v2.2.0, v3.0.2].
  - Can only install one of: cpliakas/git-wrapper[v2.0.0, v3.0.2].
  - Can only install one of: cpliakas/git-wrapper[v2.0.1, v3.0.2].
  - Can only install one of: cpliakas/git-wrapper[v2.1.0, v3.0.2].
  - Installation request for cpliakas/git-wrapper (locked at v3.0.2) -> satisfiable by cpliakas/git-wrapper[v3.0.2].
```

As Blitz accepts `cpliakas/git-wrapper` v2 and v3 it’s as easy as `composer require cpliakas/git-wrapper:^2.2.0`, but I wondered if it were possible for Copy to use the version standard API too (i.e. be agnostic to the version that’s installed).

**Comment by ostark** [comment]
I can not see any breaking changes between 2.x and 3.x. I'll add ^3.0.
However, I wonder why there is a major version bump at all?

**Comment by joshuabaker** [comment]
Thanks, @ostark. Possible a large under-the-hood rebuild. 🤷🏻‍♂️

**Comment by ostark** [comment]
It's impossible to use both since namespaces changed.
I'll go with the 3.x, but this might take some time for testing.

**Comment by ostark** [comment]
Updated `cpliakas/git-wrapper` to `^3.0` 
https://github.com/fortrabbit/craft-copy/pull/61/files

**Comment by joshuabaker** [comment]
Legend. As always. 🙏🏻
