### ISSUE TITLE
PHP requirement incompatible on install

### ISSUE THREAD

**Issue by Objektorientert** [fortrabbit/craft-copy#62]
Trying to install plugin via composer:
`composer.phar require fortrabbit/craft-copy:^1.0.0-RC11`

My php version is 7.1.19 (cli).
Mamp pro is using 7.1.8

While trying to get plugin i get this error:
```
[InvalidArgumentException]                                                                                              
  Package fortrabbit/craft-copy at version ^1.0.0-RC11 has a PHP requirement incompatible with your PHP version (7.1.19)
```
Although stated in the readme that the php requirement is 7.1+

**Comment by ostark** [comment]
Sorry the readme is not up-to-date:
The packages r[equires PHP ^7.2](https://github.com/fortrabbit/craft-copy/blob/master/composer.json#L25), as PHP 7.1 became EOL a few months ago.

**Comment by ostark** [comment]
Have a look at the new kid on the block https://getnitro.sh/ for your local env
