### ISSUE TITLE
Drop all tables before importing

### ISSUE THREAD

**Issue by joshuabaker** [fortrabbit/craft-copy#63]
When copying down from Fortrabbit, if a plugin was installed locally but not on the remote _and_ that plugin created tables you run into issues.

Rough steps to replicate:

1. Install Craft Commerce locally
1. Sync remote database
1. Install Craft Commerce

This leads to an install migration error as the `commerce_addresses` table already exists locally.

Is it possible to completely clear the database before reimporting the downloaded database dump?

**Comment by ostark** [comment]
Since craft copy is a plugin is relies on Craft. When we drop the entire DB at some point and the import fails for some reason, you can not use craft copy anymore to restore the previous state. IMO the migration should take care of it.
