### ISSUE TITLE
Put config files in a dedicated craft-copy folder in config

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#69]
Currently config files from Craft Copy are stored on top level in the config folder. I think with Craft CMS 3.5 the "project" folder was introduced storing configs within that folder. I also noticed that other plugins have a folder in `config` with additional files in it. 

I believe to know that there can be multiple configs for Craft Copy for multiple environments.

**Comment by frank-laemmer** [comment]
Current status: Waiting for feedback.

**Comment by ostark** [comment]
okay, let's use `/config/craft-copy` to store new files, but use `/config` as a fallback for reading.

**Comment by ostark** [comment]
https://github.com/fortrabbit/craft-copy/commit/0e561519fb2c7b1846ce49fa48414fce5ef262c8
