### ISSUE TITLE
Explain before/after commands better

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#70]
There is some mention of "before/after" commands here:
https://github.com/fortrabbit/craft-copy#run-scripts-beforeafter-commands
It also links to an example file.

I would like to see explained:

* Give some examples for use cases and maybe but the examples right away in the README. 
* Is there a was to deploy assets generated by NPM build scripts, if so, how? `npm run prod` is part of the example.
* How does this relate to `fortrabbit.yml` which also allows post deploy operations. What is run in which order?
* What about `auto-migrate`? It's mentioned that auto-migrate is included and it is pre-populated for `code/down`. Why is not shown at `code/up` where it will also run (magically)?

**Comment by frank-laemmer** [comment]
Current status:

- [x] Some better example in REAMDE including a use case
- [ ] More useful examples in the example file

**Comment by ostark** [comment]
solved in https://github.com/fortrabbit/craft-copy/commit/c66e6e5b82ded97b64648d7c68d647b74c8ebb23
