### ISSUE TITLE
Reconsider .gitignore functionality

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#77]
I think the `.gitignore` parts of Craft Copy are mostly historic? Maybe Craft Copy does not need to modify a local `.gitignore` file? Less magic is maybe better.

* [Craft CMS original .gitignore file](https://github.com/craftcms/craft/blob/master/.gitignore)
* [Craft Copy .gitignore file](https://github.com/fortrabbit/craft-copy/blob/assets/src/.gitignore.example)

## Will it ever be used?

The .gitignore file from Craft Copy seems only to get created when there is no file present. I most common install scenarios the standard file will be present, only maybe in cases where someone uses SFTP to deploy not, but then it shouldn't matter.

## Database backups

Craft Copy creates local database dumps for fallback if an import/export is not working out. Those backups should be excluded from version control of course. Maybe there is a good alternative place to put those backups? When I run the craft cli command `php craft backup/db` it put's the backups in:  `storage/backups/happy-lager--2020-08-24-110719--v3.5.2.sql`

## Assets folder

Since asset Volumes are now getting ignored by default from Craft CMS and Craft Copy does not anticipate a folder called assets any more, that can hopefully be removed. 

## Editor defaults and misc

There are some excludes for IDEs and OS specific files included. While those are handy, they change and it probably should not be the role of Craft Copy to take care of this. It highly depends on the users preferences and tooling.

There are other boilerplate files like:

* https://github.com/evanwarner/craft-boilerplate/blob/develop/.gitignore
* https://github.com/venveo/craft-boilerplate/blob/master/.gitignore

**Comment by frank-laemmer** [comment]
New insights:

* `.gitignore` will only be created when no other `.gitignore` is in place.
* db file backups are getting stored in top level storage
* in some cases the `vendor` folder is not excluded from Git

**Comment by frank-laemmer** [comment]
Proposal:

* Make it also add things to an existing file
* Required: `/.env`, `vendor` folder and `*.sql`

**Comment by ostark** [comment]
Solution:

* create .gitignore if no file exist in project root
* if it does not contain a rule to ignore *.sql files, add it
* no assumptions of the base path, like web/assets anymore
* create .gitignore if no file exists in each local volume folder
