### ISSUE TITLE
Document my.conf file

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#78]
I understand that Craft Copy creates a `my.conf` file in project root. Please share why this is required and what it is used for. I think it has to do with different versions of MySQL.

**Comment by ostark** [comment]
Mainly to prevent GTID issues when importing the dump:
https://stackoverflow.com/questions/44015692/access-denied-you-need-at-least-one-of-the-super-privileges-for-this-operat/44015870

**Comment by frank-laemmer** [comment]
As discussed column stats should also be included with the file.

* column stats is for making mysqldump more compatible with different versions of MySQL (dump)? Maybe not required any more.
* "GTID purge off" would require super privileges https://help.poralix.com/articles/mysql-access-denied-you-need-the-super-privilege-for-this-operation - this is for craft copy/db/up

**Comment by frank-laemmer** [comment]
Can be documented now in README with the information provided here.

**Comment by ostark** [comment]
inline https://github.com/fortrabbit/craft-copy/commit/ca42b3d6061ede31cd90f89475046e0cae9d77b0
