### ISSUE TITLE
Document and reconsider Git remote creation

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#79]
I see that Craft Copy is creating a remote when using `code/up` with the name of the App as remote name. However, the [fortrabbit Craft CMS Git deploy install guide](https://help.fortrabbit.com/craft-3-deploy-git#toc-deploy-the-craft-code-base-with-git) suggest to add a remote by the name `fortrabbit`. 

So in many scenarios one can end up have multiple remotes with different names but the same target. Isn't that confusing?

```
$ git remote -v
appname        appname@deploy.eu2.frbit.com:appname.git (fetch)
appname        appname@deploy.eu2.frbit.com:appname.git (push)
fortrabbit     appname@deploy.eu2.frbit.com:appname.git (fetch)
fortrabbit     appname@deploy.eu2.frbit.com:appname.git (push)
```

* The fortrabbit install guides could be re-written to use the App name as the remote name as well.
* The creation of the remote is not documented yet.

**Comment by frank-laemmer** [comment]
When using `code/up` you will get asked each time which remote to push up.

**Comment by ostark** [comment]
> many scenarios
???

**Comment by frank-laemmer** [comment]
See the output. There are two remotes. One is called "appname" the other one "fortrabbit". They are both the same.

**Comment by ostark** [comment]
Solved in https://github.com/fortrabbit/craft-copy/commit/690a964c21a22da466361269b2ca7a3f16d945b3

**Comment by frank-laemmer** [comment]
The [fortrabbit multi staging article](https://help.fortrabbit.com/multi-staging) uses `production` and `staging` …
