### ISSUE TITLE
Rethink copy/setup

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#80]
`php craft setup` What is it actually supposed to do? 

The documentation says it connects the local App with the fortrabbit App. Based on that I would have guessed it: 

* asks for the App name, checks for the App
* see if it can access the App
* ( checks the security key ) 
* and maybe prints the config table

I have connected an empty App. I see it first checked if the connection to the App worked (SSH & MySQL) and then found out that the Craft Copy plugin is not installed on remote:

`The plugin is not installed with your App! Do you want to deploy now? (yes/no) [yes]:`

This will not only install the plugin, but will install the whole Craft CMS on it's way. So it will push code and dump the database and import it on the App. It will however NOT sync the volumes. So instead of only installing the plugin it did a lot of other operations, but also did not fully installed Craft for me.

### Suggestions

* End the setup with connecting the local dev env and the fortrabbit App
* Print the environment check at the end of the process
* ( Be more strict about the setup, make sure all requirements are met before start using the tool )
* Gather more information about the App on fortrabbit like:
  * Craft CMS is installed / not installed
  * The local development env is behind / ahead in Git
  * Craft Copy plugin is installed / not installed on the App
* Suggest to run `php craft copy/all/up` or down as a next step

Or the other way around: copy/setup will not only create the connection between the local dev env and the fortrabbit App but also fully install and copy over everything. 

For the state it is currently in: the documentation should be updated and the wording for installing the plugin as well.

**Comment by ostark** [comment]
Okay, let's limit the scope of `copy/setup` and point the user to `copy/all/up`

**Comment by ostark** [comment]
https://github.com/fortrabbit/craft-copy/commit/323edd74a4040c0da909c6ff606fc2bf3336328c
