### ISSUE TITLE
Have craft/copy/status command - to show the current state

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#82]
* Let's say you set up Craft Copy correctly (setup) a while ago and now you haven't been working on a project for some time. Editors have created entries and you want to get to know if your local version is up-to-date.
* Or you have been doing changes locally, but you are not sure what you have touched any more.

You'd like to know what the current state is:

```shell
php craft copy/status

* Your local Git version is 5 commits behind:
  craft copy/code/down

* Your local database is behind:
  craft copy/db/down

* Your volumes are up-to-date
  no action required
```

**Comment by ostark** [comment]
* a "diff" of the database is impossible
* volumes/down has a --dry-run flag, but collecting the "diff" can be expensive
* the suggested checks is only possible for code (runing something like `git fetch && git log HEAD..origin/master`)

**Comment by frank-laemmer** [comment]
Ooops. I thought there might be some metadata time stamp for any MySQL, or some global last update date even in a table. Hm. Maybe close. With Git it's easy to roll back. Volume assets all get added. Just MySQL can be destructive, because it's all or nothing. But there is a backup.
