### ISSUE TITLE
Craft Copy GUI

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#84]
In addition to be a command line tool — I think — it would be nice if Craft Copy could offer a user interface that is accessible with settings from within the Craft CMS control panel. So it could help users who are not so used to work in Terminal. 

In a first release it might just display some information, maybe given on the environment the plugin has detected to run in with a link to the README on using it. In a next step it might display the configuration table.

This could sequentially be extended so that all important features are implemented within the GUI. Imagine a `deploy all to fortrabbit` button.

**Comment by ostark** [comment]
Probably not in the near future.

**Comment by ostark** [comment]
Wait, I'm done already 😎

```
<html>
<form>
  <button type="submit" class="btn btn-primary">Deploy all to fortrabbit</button>
</form>
</html>
```
