### ISSUE TITLE
Plugin not installed error

### ISSUE THREAD

**Issue by alexpestell** [fortrabbit/craft-copy#85]
I receive a "plugin not installed" error when pulling in craft-copy via Composer *before* pushing the repo to a fresh fortrabbit App. 

STR follows (it is longer than it could be simply because I've included every step, including starting a `ddev` container - these can be ignored):

1. `composer create-project craftcms/craft test --ignore-platform-reqs`
2. `cd test`
3. `ddev config` (with default settings) & `ddev start` (also `ddev auth ssh` to allow access to your machine's ssh keys for later)
4. `ddev ssh` to enter container
5. `./craft setup` (enter ddev MySQL details, all `db`)
6. Craft CMS site is now working locally
7. `exit` container.
8. `composer config platform --unset`
9. `composer require fortrabbit/craft-copy:^1.0.0-RC11 --ignore-platform-reqs`
10. `ddev shh` back into container
11. `./craft plugin/install copy`
12. Now create a Uni App in fortrabbit dashboard, with Craft CMS preset.
13. `exit` container
14. `git init`; `git remote add fortrabbit alex-craft@deploy.eu2.frbit.com:alex-craft.git`
15. `git add .`; `git commit -m 'WIP'; `git push -u fortrabbit master`
16. fortrabbit App now showing "Service unavailable", so we need to copy database 
17. `ddev ssh` back into container
18. `./craft copy/setup`
19. Setup completes with message "Craft was detected on remote"
20. `./craft copy/db/up`
21. Fails with error "Plugin is not installed on remote."

**Comment by ostark** [comment]
When the code is there (on the remote), but the plugin is not installed (basically a flag in the db), "Plugin is not installed on remote." is that's technically correct.

`craft copy/db/up` needs the plugin to be installed on the remote to insert the MySQL dump there. To prevent this chicken-egg-problem there is a `--force` which is a bypass of Craft and the plugin. It uses this script instead: https://github.com/fortrabbit/craft-copy/blob/master/bin/craft-copy-import-db.php

The error message could be better.

**Comment by frank-laemmer** [comment]
Loosely related: https://github.com/fortrabbit/craft-copy/issues/83#issuecomment-680775877

**Comment by frank-laemmer** [comment]
* Wording: "on remote" > "on the fortrabbit App"
* Actions for each error?

**Comment by ostark** [comment]
Solved in other tickets.
