### ISSUE TITLE
Print a warning when trying to run Craft Copy on the fortrabbit App

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#87]
I speak with Craft Copy users in our support channel. There seems to be some confusion how and where Craft Copy works. We have now tried to highlight in the REAMDE of Craft Copy that Craft Copy should always be run locally.

But I believe some users will still try to run it on the App itself. Therefore I suggest here to catch that error and print out an error or maybe just a warning like:

```
Looks like you are trying to run Craft Copy on the fortrabbit. That's not how it usually works. Best run Craft Copy with your local development environment. More here: https://github.com/fortrabbit/craft-copy#workflow
```

**Comment by tomdavies** [comment]
warn if `APP_SECRETS` env var set

**Comment by frank-laemmer** [comment]
https://github.com/fortrabbit/craft-copy/pull/119
