### ISSUE TITLE
Deployment not applying YAML properly in 3.5.7

### ISSUE THREAD

**Issue by compass360** [fortrabbit/craft-copy#88]
After updating local version of Craft (from 3.3.18.1 to 3.5.7) and redeploying via copy/code/up (RC11), our site's project config YAML was not applied.

In the Craft CP's Project Config section ([/admin/utilities/project-config](https://imgur.com/a/GAq9K8Y)), there are a number of big changes being shown (note that the jump from 3.3 to 3.5 is a drastic update to how YAML is integrated into Craft) that I am unable to apply via the "Apply Changes" or "Reapply Everything" buttons – clicking either button takes a second before a "All done!" message appears, but returning to this Project Config still shows the same changes waiting to be applied.

Somehow, redeploying again via a second copy/code/up applies the YAML config and we're good to go - nothing appearing in the Project Config window, and I can check the DB directly to see that the changes have been applied. 

Unfortunately, after hoping this might have been a one-time occurrence related to the update from 3.3 to 3.5, the same issue arose a second time after making a minor modification to a setting locally and pushing live. Again, redeploying with a second copy/code/up solved it.

Speaking with Craft/P&T support, the first suggestion might be that this is related to cacheing: "Craft 3.5 did start caching project config data a lot more heavily... it almost sounds like it needs to manually clear caches upon deployment or some such."

**Comment by frank-laemmer** [comment]
I think I ran into this issue as well with my little live project.

1.  I deployed with craft auto migrate to my fortrabbit App. 
2. I logged in to the Control Panel. It showed a warning that new changes are in YAML
3. When clicking on review I got this (new?) screen with a diff of changes and multiple options, like "apply new stuff only" or "reply everything"

My Craft version is now 3.5.8. Craft Copy is on "dev-assets".

Here is the first two steps:

<img width="1135" alt="Screenshot 2020-09-02 at 17 24 55" src="https://user-images.githubusercontent.com/962736/92004103-19851d00-ed42-11ea-90c6-271a26f8cadc.png">

**Comment by compass360** [comment]
Yes, it appears this is a new screen (not sure if new to 3.4 or 3.5, since we effectively jumped right from 3.3 to 3.5). 

Now, from here, does Craft allow you to apply the changes from this diff page?

**Comment by ostark** [comment]
solved in https://github.com/fortrabbit/craft-copy/commit/455cbad03fe09cd17dc9fecd548ca00ea5bd36e3

**Comment by compass360** [comment]
Thanks!
