### ISSUE TITLE
Better catch common MySQL issues

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#89]
As discussed [here](https://github.com/fortrabbit/craft-copy/issues/83), there might be some gotchas with MySQL one can easily run into, especially when setting things up. Those errors might be better caught so that a more meaningful and actionable error can be printed to screen.

**Comment by frank-laemmer** [comment]
https://github.com/fortrabbit/craft-copy/blob/assets/src/Actions/DbUpAction.php#L82

**Comment by frank-laemmer** [comment]
* Needs some re-editing of wording: "Make **sure** to deploy …"
* Should catch "Plugin not installed"

**Comment by ostark** [comment]
Reviewed. Looks okay already.
