### ISSUE TITLE
Catch "password auth" and display an error or a warning

### ISSUE THREAD

**Issue by frank-laemmer** [fortrabbit/craft-copy#91]
Case, I am trying to setup Craft Copy but I don't have my SSH keys installed correctly (in my case I was running DDEV and the keys have not be installed in the container). I was trying to run `php craft copy/setup`.

During setup it asked for my SSH password. That's the fallback when SSH keys didn't worked out. But this can not work ever here, since the URL Craft Copy is trying to use the fortrabbit SSH URL without the cryptic string (for username auth).

It would be better if Craft Copy would catch the ssh password prompt and display a message that this won't work at all. The README also states that SSH Key auth is a requirement. So it should not even try with username/password.

**Comment by ostark** [comment]
I wasn't able to catch the prompt.
