### ISSUE TITLE
The install/plugin command is deprecated

### ISSUE THREAD

**Issue by TheFunkyMonk** [fortrabbit/craft-copy#92]
Super minor issue, but just a heads up that it looks like `install/plugin` should be swapped out for `plugin/install` in the readme.

<img width="458" alt="Screen Shot 2020-09-24 at 11 15 57 AM" src="https://user-images.githubusercontent.com/1728770/94183609-88442a80-fe57-11ea-84f1-2f2b7fc26531.png">

**Comment by ostark** [comment]
Thanks @TheFunkyMonk 
it's already fixed on this feature branch https://github.com/fortrabbit/craft-copy/tree/assets#installation
