### ISSUE TITLE
How to get the returned ExitCode using PHP shell_exec?

### ISSUE THREAD

**Issue by bransinanderson** [fortrabbit/craft-copy#94]
Using shell_exec in PHP, how can I get the ExitCode to know whether a deployment was successful or failed? The result of $shell_db_down returns the output of the "Performed steps" string, but I need to be able to grab the return ExitCode::OK of the DbDownAction.

Is this possible?

```
<?php
$shell_db_down = shell_exec("
	yes | php ./craft copy/db/down dev
");

PHP_EOL;
echo '=======================================';
print_r($shell_db_down);
echo '=======================================';
PHP_EOL;
```

**Comment by ostark** [comment]
https://stackoverflow.com/questions/1941755/getting-output-and-exit-status-from-shell-exec
